// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OpsTrack_API.Migrations
{
    [DbContext(typeof(OpsTrackContext))]
    [Migration("20250919191452_someNewMigrationToDebug")]
    partial class someNewMigrationToDebug
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OpsTrack_API.Models.ConnectionEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("GameIdentity");

                    b.ToTable("ConnectionEvents");
                });

            modelBuilder.Entity("OpsTrack_API.Models.Player", b =>
                {
                    b.Property<string>("GameIdentity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.HasKey("GameIdentity");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("OpsTrack_API.Models.ConnectionEvent", b =>
                {
                    b.HasOne("OpsTrack_API.Models.Player", "Player")
                        .WithMany("ConnectionEvents")
                        .HasForeignKey("GameIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpsTrack_API.Models.Player", b =>
                {
                    b.Navigation("ConnectionEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
