name: Build and Publish API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore and build .NET solution
      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # 4. Optional: run unit tests if you have them
      # - name: Test
      #   run: dotnet test --no-build --configuration Release

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t opstrack_api:latest .

      # 6. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Tag Docker image for GHCR
      - name: Tag Docker image
        run: docker tag opstrack_api:latest ghcr.io/opstrackreforger/opstrack_api:latest

      # 8. Push Docker image to GHCR
      - name: Push Docker image
        run: docker push ghcr.io/opstrackreforger/opstrack_api:latest
